## Import Libraries

In [ ]:
#Libraries
import numpy as np
import pandas as pd

## Ignore Warnings

In [ ]:
import warnings
warnings.filterwarnings("ignore")

## Read Data

In [ ]:
#extract data
movieMetadata = pd.read_csv("movies_metadata.csv")
movies = pd.read_csv("movies.csv")
ratings = pd.read_csv("ratings.csv")

#display data
movieMetadata.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [ ]:
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [ ]:
ratings.head()

   userId  movieId  rating   timestamp
0       1       31     2.5  1260759144
1       1     1029     3.0  1260759179
2       1     1061     3.0  1260759182
3       1     1129     2.0  1260759185
4       1     1172     4.0  1260759205

## Merge the Data

In [ ]:
#merged the movies and ratings by movieId
merged = movies.merge(ratings, on="movieId")

#display
merged.head()

,movieId,title,genres,userId,rating,timestamp
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,7,3.0,851866703
1,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,9,4.0,938629179
2,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,13,5.0,1331380058
3,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,15,2.0,997938310
4,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,19,3.0,855190091

In [ ]:
#clean the movie name and create in the new column:

#remove (year) at the title in merged data
merged["movie_title"] = [movie.split(" (")[0] for movie in merged["title"]]

#rename column tittle in movieMetadata
movieMetadata.rename(columns = {'title':'movie_title'}, inplace = True)

#merged both dataset
movieNew = merged.merge(movieMetadata, how="right",on="movie_title")

#display new data farme
movieNew.head()

,movieId,title,genres_x,userId,rating,timestamp,movie_title,adult,belongs_to_collection,budget,...,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,video,vote_average,vote_count
0,1.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,7.0,3.0,8.518667e+08,Toy Story,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,...,"[{'iso_3166_1': 'US', 'name': 'United States o...",1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,False,7.7,5415.0
1,1.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,9.0,4.0,9.386292e+08,Toy Story,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,...,"[{'iso_3166_1': 'US', 'name': 'United States o...",1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,False,7.7,5415.0
2,1.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,13.0,5.0,1.331380e+09,Toy Story,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,...,"[{'iso_3166_1': 'US', 'name': 'United States o...",1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,False,7.7,5415.0
3,1.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,15.0,2.0,9.979383e+08,Toy Story,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,...,"[{'iso_3166_1': 'US', 'name': 'United States o...",1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,False,7.7,5415.0
4,1.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,19.0,3.0,8.551901e+08,Toy Story,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,...,"[{'iso_3166_1': 'US', 'name': 'United States o...",1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,False,7.7,5415.0

## Explore the Data

In [ ]:
print('No of attributes: ', len(movieNew.columns))
print('No of rows: ', len(movieNew))

No of attributes:  30
No of rows:  127283

In [ ]:
movieNew.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 127283 entries, 0 to 127282
Data columns (total 30 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   movieId                89286 non-null   float64
 1   title                  89286 non-null   object
 2   genres_x               89286 non-null   object
 3   userId                 89286 non-null   float64
 4   rating                 89286 non-null   float64
 5   timestamp              89286 non-null   float64
 6   movie_title            127277 non-null  object
 7   adult                  127283 non-null  object
 8   belongs_to_collection  26290 non-null   object
 9   budget                 127283 non-null  object
 10  genres_y               127283 non-null  object
 11  homepage               28972 non-null   object
 12  id                     127283 non-null  object
 13  imdb_id                127266 non-null  object
 14  original_language      127272 non-null  object
 15  original_title         127283 non-null  object
 16  overview               126236 non-null  object
 17  popularity             127278 non-null  object
 18  poster_path            126893 non-null  object
 19  production_companies   127280 non-null  object
 20  production_countries   127280 non-null  object
 21  release_date           127187 non-null  object
 22  revenue                127277 non-null  float64
 23  runtime                127020 non-null  float64
 24  spoken_languages       127277 non-null  object
 25  status                 127189 non-null  object
 26  tagline                90665 non-null   object
 27  video                  127277 non-null  object
 28  vote_average           127277 non-null  float64
 29  vote_count             127277 non-null  float64
dtypes: float64(8), object(22)
memory usage: 30.1+ MB

## Drop Unnecessary Column

In [ ]:
movieNew.drop(["title","genres_x","timestamp","adult","homepage","id","original_title",
               "overview","poster_path","tagline","video","belongs_to_collection"], axis=1, inplace=True)

## Checking Data

In [ ]:
#checking null
movieNew.isnull().sum()

movieId                 37997
userId                  37997
rating                  37997
movie_title                 6
budget                      0
genres_y                    0
imdb_id                    17
original_language          11
popularity                  5
production_companies        3
production_countries        3
release_date               96
revenue                     6
runtime                   263
spoken_languages            6
status                     94
vote_average                6
vote_count                  6
dtype: int64

In [ ]:
movieNew.dropna(inplace=True)

In [ ]:
#recheck null
movieNew.isnull().sum()

movieId                 0
userId                  0
rating                  0
movie_title             0
budget                  0
genres_y                0
imdb_id                 0
original_language       0
popularity              0
production_companies    0
production_countries    0
release_date            0
revenue                 0
runtime                 0
spoken_languages        0
status                  0
vote_average            0
vote_count              0
dtype: int64

In [ ]:
#checking duplicate
movieNew[movieNew.duplicated(keep=False)]

Empty DataFrame
Columns: [movieId, userId, rating, movie_title, budget, genres_y, imdb_id, original_language, popularity, production_companies, production_countries, release_date, revenue, runtime, spoken_languages, status, vote_average, vote_count]
Index: []

## Clean Data Exploration

In [ ]:
print('New no of attributes: ', len(movieNew.columns))
print('New no of rows: ', len(movieNew))

New no of attributes:  18
New no of rows:  89264

## Export Clean Data to csv

In [ ]:
#write to csv
from csv import writer
movieNew.to_csv('Movies Clean.csv', index=False)